// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgUB3RiEk7s-t6D-iors0tIr6fcfLr2Do',
    appId: '1:15572405989:web:e640ce6683b8752db84e0c',
    messagingSenderId: '15572405989',
    projectId: 'space-cube-2d524',
    authDomain: 'space-cube-2d524.firebaseapp.com',
    storageBucket: 'space-cube-2d524.appspot.com',
    measurementId: 'G-ERZ56E9PL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2n9239nSBOb6vGSd0azh-mXJ9VntGk3A',
    appId: '1:15572405989:android:5a47260c6118ee42b84e0c',
    messagingSenderId: '15572405989',
    projectId: 'space-cube-2d524',
    storageBucket: 'space-cube-2d524.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIMjKAo_Y7pKdWkDxRRdNZhCUZTan4cEY',
    appId: '1:15572405989:ios:4b909d4237585659b84e0c',
    messagingSenderId: '15572405989',
    projectId: 'space-cube-2d524',
    storageBucket: 'space-cube-2d524.appspot.com',
    iosClientId: '15572405989-340u658kgmp35bm21l131c3patfhk539.apps.googleusercontent.com',
    iosBundleId: 'com.example.kayamaza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIMjKAo_Y7pKdWkDxRRdNZhCUZTan4cEY',
    appId: '1:15572405989:ios:4b909d4237585659b84e0c',
    messagingSenderId: '15572405989',
    projectId: 'space-cube-2d524',
    storageBucket: 'space-cube-2d524.appspot.com',
    iosClientId: '15572405989-340u658kgmp35bm21l131c3patfhk539.apps.googleusercontent.com',
    iosBundleId: 'com.example.kayamaza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgUB3RiEk7s-t6D-iors0tIr6fcfLr2Do',
    appId: '1:15572405989:web:bc7180b061d789ecb84e0c',
    messagingSenderId: '15572405989',
    projectId: 'space-cube-2d524',
    authDomain: 'space-cube-2d524.firebaseapp.com',
    storageBucket: 'space-cube-2d524.appspot.com',
    measurementId: 'G-XEZEFG5QB7',
  );
}
